CREATE TABLE IF NOT EXISTS `worker_node` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `HOST_NAME` VARCHAR(64) NOT NULL,
  `PORT` VARCHAR(64) NOT NULL,
  `TYPE` INT NOT NULL,
  `LAUNCH_DATE` DATE NOT NULL,
  `MODIFIED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;