logging:
  level:
    web: DEBUG
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include:
          - health
          - info
          - mappings
  server:
    port: ${MONITOR_PORT:8081}
server:
  port: ${PORT:8081}
  servlet:
    context-path: "/"
spring:
  application:
    name: uid-breaker
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE:local}
  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/sample}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
  # flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    #baseline-version: 1.0.0
    baseline-description: Initial
    locations:
      - classpath:/db/migration
  # jpa
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
